### ISSUE TITLE
Konsep Wall-Jumping

### ISSUE THREAD

**Issue by antoniosetya** [KP-Kepra/Game-1#3]
Itu wall-jumping emang mau diadain nggak? Kalo misalnya mau tetep dipertahanin, control buat jumpnya kayaknya perlu diganti, soalnya kalo pake W sih pencetnya susah. (acis ama dika bilang sih susah, gua sendiri juga rada gak bisa)

**Comment by KP-Kepra** [comment]
Gw gaada masalah di wall-jump nya sih, tapi iya masih agak clunky, maksudny wall jump butuh control + timing yg pas biar mulus, kalo gak suka jatoh. 
Gw bilang sih sementara bikin wall jump ada dulu aja, kalau beberapa bulan kedepannya banyak masalah wall jump kita scrap aja.

**Comment by KP-Kepra** [comment]
Kayaknya isu yang lu maksud ini ton : 
Pas playernya wall-jump dari kiri ke kanan, dia lompat, dan kena tembok kanan. Secara reflek controlnya masih atas + kiri, jadi begitu nabrak tembok kanan otomatis playernya langsung jatoh ke kiri lagi.

**Comment by antoniosetya** [comment]
basically, orang susah ganti pencetannya buat ngontrol wall-jumpnya, kan lu harus pencet kanan+W, trus langsung reflek ganti kiri, langsung W lagi, dst. Itu yg bikin rada susah.

**Comment by KP-Kepra** [comment]
gw mencetnya sih AWDWAWDWA nonstop, mulus sih hasilnya.

**Comment by KP-Kepra** [comment]
Tapi kalo mau ganti control biar lebih enak gapapa ton.
kalo gitu berarti pas dia wall-jump dan kena tembok, mesti tunggu antara hold W (basically naik atas di tembok abis kena tembok karena inersia) atau gak tunggu max jump heightnya baru bisa lepas dari tembok.

**Comment by antoniosetya** [comment]
Hmmm...

**Comment by KP-Kepra** [comment]
Wall-Jump udah gw update. coba dites.

**Comment by antoniosetya** [comment]
Pantes, tadi gua tes tiba2 kok jadi gampang...

**Comment by KP-Kepra** [comment]
huehuehue sip

**Comment by antoniosetya** [comment]
close issue?
