### ISSUE TITLE
Doors & Crap

### ISSUE THREAD

**Issue by KP-Kepra** [KP-Kepra/Game-1#4]
Issue dari Anton : 
1.) ~~Multiple Doors ancur semua~~ **SOLVED**
2.) ~~Door belom bisa di door-jump~~ **SOLVED**
3.) ~~Tulisan X open door belum diatas karakter~~ **SOLVED**
4.) ~~Alternatif buat ngebuka pintu selain ancurin~~ **SOLVED**

**Comment by antoniosetya** [comment]
"Door-jump" kayaknya gua udah nemu, lgi gw coba dulu

**Comment by KP-Kepra** [comment]
nais ton.

**Comment by antoniosetya** [comment]
Udah gw update, coba dicek

**Comment by KP-Kepra** [comment]
Sipp, mulus ton :+1:

**Comment by antoniosetya** [comment]
Pintu yang didepan (deket posisi p1 pertama kali), kalo jatoh diatasnya gamenya nge-freeze, tuh...

**Comment by antoniosetya** [comment]
Meh, fixed..

**Comment by KP-Kepra** [comment]
Oiya dat bug lel
